#!/usr/bin/env bash
#Bash script that archives all MySQL database with the help of mysqldump and tar
mysqldump --all-databases -u root --password="$1" > backup.sql
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"
tar -czvf "$file_name" backup.sql)".tar.gz backup.sql
