#!/usr/bin/env bash
#Bash script that archives all MySQL database with the help of mysqldump and tar
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
