#!/usr/bin/env bash
# program for checking status about a file
file="school"
if [ -f "$file" -o -b "$file" -o -c "$file" -o -d "$file" ]; then
	echo "$ school file exists"
	if [ -f "$file" ]; then
		if [ "$(wc -c $file)" != "0" ]; then
			echo "school file is not empty"
		else
			echo "school file is empty"
		fi
		echo "school is a regular file"
	else
		echo "school is not empty"
	fi
else
	echo "school file does not exist"
fi

