#!/usr/bin/env bash
# Will fix a web server to Nginx as Nginx user listening on port 8080.
sudo sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/g" etc/nginx/sites-available/default
sudo chmod ugo+wrx /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx start
